defaults:
  - _self_
  - experiment: mnist
seed: 43
n_workers: 1
use_seeds: false
use_instances: true
output_dir: /autosparse/out

#------------------------- Hydra Config ------------------------#
hydra:
  output_subdir: null  
  run:  
    dir: /autosparse/out/logs
    # dir: out/logs